Repository 9oormthon-univ-swu/2024_SEORANGJE_ABOUTME_FE, pull requests merged in 2024-05, with the labels that each got.

#41 [Feat] #40 메타태그, 인앱 브라우저 우회
  aboutMe/index.html
  aboutMe/public/icons/AboutMeTmb.png
  aboutMe/src/pages/GuestPage.jsx
  aboutMe/src/pages/SigninPage.jsx
Labels: ➕ feat

#46 Feat/#43 func guest
  aboutMe/src/Components/HomePage/Folder.jsx
  aboutMe/src/pages/GuestPage.jsx
  aboutMe/src/pages/HomePage.jsx
Labels: 🐞 bug, ➕ feat

#55 [Fix] 인앱 브라우저 우회 오류 수정
  aboutMe/index.html
  aboutMe/package-lock.json
  aboutMe/package.json
  aboutMe/src/App.jsx
  aboutMe/src/pages/DiaryPage.jsx
  aboutMe/yarn.lock
Labels: 🐞 bug
